config/routes.rb
CareersCodefireComAu::Application.routes.draw do
  resources :positions

  root :to => "home#index"

end

app/models/position.rb
class Position < ActiveRecord::Base
  has_friendly_id :title, :use_slug => true
  validates_presence_of :title, :summary, :description
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :load_positions

  protected
    def load_positions
      @positions = Position.find(:all, :limit => 3, :order => 'created_at desc')
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  def show
    @position = Position.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/views/home/index.html.erb
<section id="main" role="main" class="grid_8 alpha">
      <%= link_to(image_tag("logo.png"), "http://www.codefire.com.au") %>
      <%= image_tag("hiring.png", :id => "hiring", :alt => "We're hiring!") %>
      <h2>We are looking for the best and brightest developers, designers and thinkers to join our team.</h2>
			
			<p>At CodeFire we favour attitude and intelligence over a piece of paper. You don't have to have a degree to work here &mdash; just a passion for code, the web and for working smarter.</p>
			
			<article class="clearfix">
        <%= image_tag("aus.png") %>
        <p>The <strong>CodeFire Headquarters</strong> are based in Adelaide but we also have people in Launceston and Melbourne. <em>Remote teams are right up our alley.</em> The Adelaide office is central and close to cafes, restaurants and public transport.</p>
        </article>
			
			<article class="clearfix">
        <%= image_tag("code.png") %>
        <p>We are huge fans of both Ruby and <strong>Ruby on Rails</strong> but love Javascript (almost) as much! The CodeFire team specialises in Test Driven Development, bug-free and usable software that can scale.</p>
			</article>
			
			<article class="clearfix">
        <%= image_tag("lunch.png") %>
        <p>We have regular sessions we call &#8220;Lunch and Learn&#8221; &mdash; have a bite to eat and add a few new tricks to the toolbox. We believe in fostering personal development and CodeFire employees frequently get time to learn new things.</p>
			</article>
			
			<article class="clearfix">
        <%= image_tag("mac.png") %>
        <p>Our toolset includes Git, Jira, Bamboo, Harvest, Skype and Highrise. We develop on Mac and Linux and some of the guys even use Vim for all of their coding :)</p>
			</article>
			
			<article class="clearfix">
        <%= image_tag("fun.png") %>
        <p><em>One of the most important things at Codefire is to have fun. We're all passionate folks and we love what we do!</em></p>
			</article>
			
    </section>
		

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="js flexbox canvas canvastext webgl no-touch geolocation postmessage websqldatabase no-indexeddb hashchange history draganddrop websockets rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients cssreflections csstransforms no-csstransforms3d csstransitions fontface video audio localstorage sessionstorage webworkers applicationcache svg inlinesvg smil svgclippaths wf-proximanova1proximanova2-n4-active wf-proximanova1proximanova2-i4-active wf-proximanova1proximanova2-n7-active wf-proximanova1proximanova2-i7-active wf-leaguegothic1leaguegothic2-n4-active wf-active" lang="en"><!--<![endif]--><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults, "ga", "modernizr-1.7.min.js", "gru2owo" %>
  <%= csrf_meta_tag %>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title>CodeFire | We're hiring! <%= @position.try(:title) %></title>
  <meta name="description" content="">
  <meta name="author" content="">

  <meta name="viewport" content="width=960px">
  <link rel="shortcut icon" href="/images/favicon.ico">

  <meta property="fb:page_id" content="88148893364" />

	<style type="text/css">.tk-proxima-nova{font-family:"proxima-nova-1","proxima-nova-2",sans-serif;}.tk-league-gothic{font-family:"league-gothic-1","league-gothic-2",sans-serif;}</style><link rel="stylesheet" href="http://use.typekit.com/k/gru2owo-d.css?3bb2a6e53c9684ffdc9a9bf0135b2a625599d48bf0f321e90d6570f5c656e9f21d4bb8f0448791a3724ee1a2807642185f1dcefcc4d571a68cca1ff9c9e6d1935d2afc34149ce4966ab66823752260e079b2e6efbfaaeb210d6e917aacfc0cb79d84f107744b9eea55102e78019ec98ad75e086fed4fc95f630f46a620d06f3fe1494c7670c77d457c4027972b5033cf511d13df6a7373f623a8c0dfd3ae1084dd485a887d8494a517"><script type="text/javascript">try{Typekit.load();}catch(e){}</script>
</head>

<body>

  <div id="container" class="container_12">
    <header>

    </header>

    <%= yield %>

		<aside class="grid_4">
			<h2>Empty Chairs</h2>
			
      <%= render(@positions) %>
			
			<article id="apply">
				<p>To apply for any of the positions we have vacant, just drop us a line on <a href="mailto:careers@codefire.com.au">careers@codefire.com.au</a> — we can't wait to hear from you!</p> 
			</article>
			
			<article id="pics">
				<h2>Life at Codefire</h2>
				<img src="/images/stand_up.png" alt="Daily stand up meeting" />
				<img src="/images/stair_climb.png" alt="Westpac stair climb" />
				<img src="/images/cafe.png" alt="Working from wherevs" />
			</article>

		</aside>
		
    
  </div> <!-- eo #container -->

	<footer>
		<div class="container_12">
			
			<div class="grid_6 alpha">
				<a href="http://twitter.com/codefire" target="_blank"><img class="icon" src="/images/twitter.png" alt="Follow us on Twitter"></a>
				<a href="http://www.facebook.com/pages/CodeFire/88148893364" target="_blank"><img class="icon" src="/images/fb.png" alt="Like us on Facebook"></a>
				<p>careers@codefire.com.au</p>
			</div>
			
			<div class="grid_6">
				<a href="http://codefire.com.au/" target="_blank"><img src="/images/logo-reverse.png"></a>
			</div>
			
		</div>
		
  </footer>

  <script>
    var _gaq=[["_setAccount","UA-22675020-2"],["_trackPageview"]]; 
    (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];g.async=1;
    g.src=("https:"==location.protocol?"//ssl":"//www")+".google-analytics.com/ga.js";
    s.parentNode.insertBefore(g,s)}(document,"script"));
  </script>

</body>
</html>

app/views/positions/_position.html.erb
<article>
  <h3><%= position.title %></h3>
  <%= image_tag("chair.png") %>
  <p><%= position.summary %></p>
  <p><%= link_to("read more", position_path(position), :class => 'read-more') %></p>
</article>

app/views/positions/show.html.erb
		<section id="main" role="main" class="grid_8 alpha">
      <%= link_to(image_tag("logo.png"), root_path) %>

      <h1><%= @position.title %></h1>
      <h2><%= @position.summary %></h2>
      <p><%= raw(@position.description) %></p>
			
			<div id="apply-email">
				<p><strong>Email your application to <a href="mailto:careers@codefire.com.au">careers@codefire.com.au</a></strong></p>
			</div>
			
      <a href="http://twitter.com/share" class="twitter-share-button" data-count="none" data-via="codefire" data-related="adelaiderb:Adelaide Ruby User Group">Tweet</a><script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
      <iframe src="http://www.facebook.com/plugins/like.php?href=<%= position_url(@position) %>&amp;send=false&amp;layout=button_count&amp;width=450&amp;show_faces=false&amp;action=recommend&amp;colorscheme=light&amp;font=arial&amp;height=35&amp;ref=<%=@position.to_param %>" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:450px; height:25px;" allowTransparency="true"></iframe>
    </section>